site_name: Butler documentation
repo_url: https://github.com/mountaindude/butler
site_url: https://mountaindude.github.io/butler/
site_description: Butler extends Qlik Sense with various data connectivity and monitoring features.
google_analytics: ['UA-58487795-2', 'mountaindude.github.io/butler']
pages:
- Home: index.md
- Overview and features: overview.md
- Getting started: getting-started.md
- Project layout: project-layout.md
- Installation and configuration: install-config.md
- Running Butler: running.md
- Features:
  - REST API: rest.md
  - Log event handlers: log-events.md
  - MQTT integration: mqtt.md
- Security considerations: security.md
- Tools used: tools-used.md
theme: readthedocs
markdown_extensions:
    - toc:
        permalink: True
        separator: "_"
