---
Butler:
  # Possible log levels are silly, debug, verbose, info, warn, error
  logLevel: debug

  slackConfig:
    webhookURL: <fill in your web hook URL from Slack>
    loginNotificationChannel: sense-user-activity
    taskFailureChannel: sense-task-failure
  mqttConfig:
    brokerHost: <FQDN or IP of MQTT server>
    brokerPort: 1883
    taskFailureTopic: qliksense/task_failure
    taskFailureServerStatusTopic: qliksense/butler/task_failure_server
    sessionStartTopic: qliksense/session/start
    sessionStopTopic: qliksense/session/stop
    connectionOpenTopic: qliksense/connection/open
    connectionCloseTopic: qliksense/connection/close
    sessionServerStatusTopic: qliksense/butler/session_server
    activeUserCountTopic: qliksense/users/active/count
    activeUsersTopic: qliksense/users/active/usernames
  udpServerConfig:
    serverIP: <FQDN or IP of server where Butler is running>
    portSessionConnectionEvents: 9997
    portTaskFailure: 9998
  restServerConfig:
    serverPort: 8080
  configEngine:
    engineVersion: 12.170.2        # Qlik Associative Engine version to use with Enigma.js
    server: <FQDN or IP of Sense server where Sense Engine is running>
    serverPort: <Port to connect to, usually 4747>
    isSecure: true
    headers:
      X-Qlik-User: UserDirectory=Internal;UserId=sa_repository
    cert: <Path to cert file>
    key: <Path to key file>
    rejectUnauthorized: false
  configQRS:
    authentication: certificates
    host: <FQDN or IP of Sense server where QRS is running>
    useSSL: true
    port: 4242
    headerKey: X-Qlik-User
    headerValue: UserDirectory=Internal; UserId=sa_repository
    cert: <Path to client.pem>
    key: <Path to client_key.pem>
    ca: <Path to root.pem>
  qvdPath: <Path to folder under which QVDs are stored>
  gitHub:
    host: api.github.com
    pathPrefix: ''
  