language: node_js
node_js:
  - node
env:
  - NODE_ENV=production
notifications:
  slack:
    rooms:
      - secure: "h1ELLwWu1P8u4aLjbyISIe0K/xMRWovbGMxKfRHTsaTaudxSQ6Pbb1kmjFrtVUKSIdxdPS4k5JwY+YIMK5TbUql+gdPQ+WYSG9pdQUE3HeednhpE5XkbSUFQKFxw9a0QNdnslpm6MO8Qz5HtTjJWPhgVNZkNErvt9lH8/3Lg7xxneanJV/dCQ9fB/zdgtci5p18DjzjAqyT8pGzV3qVaoDF5XQrsdYwm+adUombWxBpLQGcybetB6xqpHMu/j9sPbdXfr4Ain+R+PBf3YnmR/iaCbHhvY38vvZbgEVo2WY9tMO0+pdZzsiMJ7lijuNT56HnsSd+uG7joCXHAp/Z5l2uiCc1H/DKoQmfk0qeQPsSx5ieocM9nlQuzrlouq97EnC1SzOGzFlRDA+J2/itVQB9t14sIUY1pnuwxzbITEdytAjOeG6b3MVnmMVTHissnIjZyjpQd4Pn7km3Avy0htdvBe9loUUrnceMF99bFPW8AK9QFV02WiKe0Md0OJ8hznxNWVuoMu6XZLdSB34SpdRgiptu7ghk+wvGmQFrFKe9uOwAyGSfJP9UF/yPvRRwhlt0ryFptU4zWVokDe9hMVuMctZFdWhTCrbIHXVwY98qzWC4Pqs5SLqW5MxWXMkP+AMEvBy+mswopEquMzREvslngzKODvtzSX5afVaOdtOg="
    on_success: always
    on_failure: always
    on_pull_requests: true
