# docker-compose.yml
version: '3.3'
services:
  butler:
    image: ptarmiganlabs/butler:3.0.1
    container_name: butler
    restart: always
    ports:
      - "8080:8080"     # REST API available on port 8180 to services outside the container
      - "9997:9997"     # UDP port for session connection events
      - "9998:9998"     # UDP port for task failure events
    volumes:
      # Make config file accessible outside of container
      - "./config:/nodeapp/config"
    environment:
      - "NODE_ENV=production"
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: "5m"

